runtime: python36
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /.*
  script: index.main

- url: /static
  static_dir: static
  expiration: 30d

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
# [END libraries]


#handlers:
#- url: /static
#  static_dir: static
#  expiration: 30d

#- url: /favicon.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico
#  expiration: 30d
